# -*- coding: utf-8 -*-
"""Machine learning 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1Jw1ZxCOaofS2h7N8kCasp_KCc7jQh6
"""

import numpy as np
marks = np.array([65, 72, 81, 69, 90])
print(marks)
print("Mean =", np.mean(marks))
print("Maximum =", np.max(marks))
print("Minimum =", np.min(marks))

name = "Rahul"
age = 21
percentage = 78.5
print(name)
print(age)
print(percentage)

age = 21
percentage = 82.5
name = "Amit"
passed = True
print(type(age))
print(type(percentage))
print(type(name))
print(type(passed))

marks = [65, 72, 81, 69, 90]
print(marks)
print("First mark =", marks[0])
print("Number of students =", len(marks))

marks = 72
if marks >= 40:
 print("Pass")
else:
 print("Fail")

def calculate_average(values):
 return sum(values) / len(values)
marks = [65, 72, 81, 69, 90]
average = calculate_average(marks)
print("Average =", average)

import numpy as np
data = np.array([10, 20, 30, 40, 50])
print(data)
print("Shape:", data.shape)
print("Size:", data.size)

import numpy as np
marks = np.array([65, 72, 81, 69, 90])
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))

data = np.array([
 [2, 45],
 [4, 55],
 [6, 68],
 [8, 78],
 [10, 90]
])
print(data)
print("Shape:", data.shape)

import pandas as pd
data = {
 "Student": ["A", "B", "C", "D", "E"],
 "Study_Hours": [2, 4, 6, 8, 10],
 "Marks": [45, 55, 68, 78, 90]
}
df = pd.DataFrame(data)
print(df)

print("Average study hours:", df["Study_Hours"].mean())
print("Average marks:", df["Marks"].mean())
print("Maximum marks:", df["Marks"].max())
print("Minimum marks:", df["Marks"].min())

import matplotlib.pyplot as plt
study_hours = [2, 4, 6, 8, 10]
marks = [45, 55, 68, 78, 90]
plt.plot(study_hours, marks, marker='o')
plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.title("Study Hours vs Marks")
plt.show()

marks = [45, 55, 68, 78, 90, 62, 74, 81, 56, 69]
plt.hist(marks, bins=5)
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.title("Distribution of Marks")
plt.show()

from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data)

from sklearn.datasets import load_iris
iris = load_iris()
print("Feature names:")
print(iris.feature_names)
print("\nTarget names:")
print(iris.target_names)
print("\nDataset shape:")
print(iris.data.shape)
print("\nFirst five records:")
print(iris.data[:5])

import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(
 iris.data,
 columns=iris.feature_names
)
df["Target"] = iris.target
print(df.head())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
# Load dataset
iris = load_iris()
# Convert to Pandas DataFrame
df = pd.DataFrame(
 iris.data,
 columns=iris.feature_names
)
df["Target"] = iris.target
# Display dataset
print("First five records:")
print(df.head())
# Dataset information
print("\nDataset Shape:")
print(df.shape)
print("\nStatistical Summary:")
print(df.describe())
# NumPy operation
print("\nMean of features:")
print(np.mean(iris.data, axis=0))
# Visualization
plt.scatter(
 df["sepal length (cm)"],
 df["petal length (cm)"]
)
plt.xlabel("Sepal Length (cm)")
plt.ylabel("Petal Length (cm)")
plt.title("Iris Dataset")
plt.show()





