# -*- coding: utf-8 -*-
"""machine learning 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2igSXyW-PX6TYYSJr-J4EUD5FPjNRVM
"""

import numpy as np  # numeric arrays
import pandas as pd  # organise data into a table
import matplotlib.pyplot as plt  # plot graphs
from sklearn.model_selection import train_test_split  # split data
from sklearn.tree import DecisionTreeClassifier, plot_tree  # the model + tree visualiser
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  # evaluation



import numpy as np  # numeric arrays
import pandas as pd  # organise data into a table
import matplotlib.pyplot as plt  # plot graphs
from sklearn.model_selection import train_test_split  # split data
from sklearn.tree import DecisionTreeClassifier, plot_tree  # the model + tree visualiser
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  # evaluation
from google.colab import files  # Colab's file-upload helper
uploaded = files.upload()  # opens a Choose File dialog; pick Iris.csv

df = pd.read_csv('Iris.csv')  # load the CSV into a DataFrame
df.head()  # show first 5 rows to check the data

df = df.drop(columns=['Id'])  # the Id column carries no useful information
print(df.shape)  # (rows, columns)
print(df['Species'].value_counts())  # how many samples per class

colors = {'Iris-setosa':'red', 'Iris-versicolor':'green', 'Iris-virginica':'blue'}
for sp, c in colors.items():  # plot each species in its own colour
    subset = df[df['Species'] == sp]
    plt.scatter(subset['PetalLengthCm'], subset['PetalWidthCm'], label=sp, color=c)
plt.xlabel('Petal Length (cm)'); plt.ylabel('Petal Width (cm)')
plt.legend(); plt.show()

X = df.drop(columns=['Species'])  # all 4 measurement columns
y = df['Species']  # target: the species name

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)  # stratify keeps class balance equal
print(X_train.shape, X_test.shape)

model = DecisionTreeClassifier(criterion='entropy',  # split using Information Gain
                                max_depth=3, random_state=42)  # limit depth to avoid overfitting
model.fit(X_train, y_train)  # train the tree — no scaling needed!
print(dict(zip(X.columns, model.feature_importances_)))  # which features mattered most

y_pred = model.predict(X_test)  # predict species for unseen test data
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred, labels=model.classes_)
print('Accuracy:', acc)
print('Confusion Matrix:\n', cm)
print(classification_report(y_test, y_pred))

plt.figure(figsize=(11, 6))
plot_tree(model, feature_names=X.columns,  # draw the tree with feature/class names
          class_names=model.classes_, filled=True, rounded=True)
plt.show()

new_flower = pd.DataFrame([[5.8, 2.7, 4.1, 1.0]],  # Sepal 5.8x2.7, Petal 4.1x1.0
                          columns=X.columns)
pred = model.predict(new_flower)  # no scaling needed for a tree
print('Predicted species:', pred[0])