# -*- coding: utf-8 -*-
"""OJAS KULKARNI practical 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pe4bro07UOiYHCjGTFOf5qSarnXq-z7i
"""

import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "J"],
    "Gender": ["Male", "Female", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Male"],
    "Study_Hours": [2, 4, 5, 3, 7, 6, 8, 100, 4, 5, 5],
    "Attendance": [75, 82, 90, 68, 88, 79, 95, 92, 70, None, 78],
    "Assignments": [70, 85, 88, 65, 92, 80, 96, 90, 72, 84, 84],
    "Marks": [48, 62, 71, 45, 85, 68, 91, 89, 52, 74, 74]
}
df = pd.DataFrame(data)

print(df)

print(df.head())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

print(df.isnull())
print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x=df["Study_Hours"])
plt.title("Study Hours – Box Plot")
plt.show()

df_encoded = pd.get_dummies(
    df,
    columns=["Gender"],
    drop_first=True
)

print(df_encoded.head())

sns.histplot(df["Marks"], kde=True)

plt.title("Distribution of Marks")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()

sns.scatterplot(
    data=df,
    x="Study_Hours",
    y="Marks"
)

plt.title("Study Hours vs Marks")
plt.show()

numeric_df = df.select_dtypes(include="number")

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Create dataset
data = {
    "Student": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "J"],
    "Gender": ["Male", "Female", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Male"],
    "Study_Hours": [2, 4, 5, 3, 7, 6, 8, 100, 4, 5, 5],
    "Attendance": [75, 82, 90, 68, 88, 79, 95, 92, 70, None, 78],
    "Assignments": [70, 85, 88, 65, 92, 80, 96, 90, 72, 84, 84],
    "Marks": [48, 62, 71, 45, 85, 68, 91, 89, 52, 74, 74]
}

df = pd.DataFrame(data)

# 1. Handle missing values
df["Attendance"] = df["Attendance"].fillna(
    df["Attendance"].median()
)

# 2. Remove duplicate records
df = df.drop_duplicates()

# 3. Remove the assumed erroneous outlier
df = df[df["Study_Hours"] <= 8]

# 4. Encode categorical variable
df = pd.get_dummies(
    df,
    columns=["Gender"],
    drop_first=True
)

# 5. Separate features and target
X = df.drop(["Student", "Marks"], axis=1)
y = df["Marks"]

# 6. Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# 7. Scale numerical features
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Preprocessed training data:")
print(X_train_scaled)

print("\nTesting data:")
print(X_test_scaled)

# 8. Visualization
sns.scatterplot(
    data=df,
    x="Study_Hours",
    y="Marks"
)

plt.title("Study Hours vs Marks After Preprocessing")
plt.show()