# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QL21NRMsu660Qo_vhJ5TsYJkAQTYLGye
"""

print(df.shape)  # (rows, columns)
print(df['Purchased'].value_counts())  # how many 0s and 1s

plt.scatter(df['Age'], df['EstimatedSalary'],  # plot every user
            c=df['Purchased'], cmap='bwr', alpha=0.6)  # color by class (blue=0, red=1)
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.title('Age vs Estimated Salary (colored by Purchased)')
plt.show()

model = LogisticRegression(random_state=0)  # create an untrained model object
model.fit(X_train_scaled, y_train)  # train it: weights & bias learned here
print('Coefficients:', model.coef_)  # learned weights
print('Intercept:', model.intercept_)  # learned bias

y_pred = model.predict(X_test_scaled)  # predict class for unseen test data
acc = accuracy_score(y_test, y_pred)  # fraction of correct predictions
cm = confusion_matrix(y_test, y_pred)  # TP/TN/FP/FN table
print('Accuracy:', acc)
print('Confusion Matrix:\n', cm)
print(classification_report(y_test, y_pred))  # precision, recall, f1-score

new_customer = pd.DataFrame([[45, 110000]],  # Age=45, Salary=110000
                            columns=['Age', 'EstimatedSalary'])
new_scaled = scaler.transform(new_customer)  # scale using the SAME scaler as training
pred = model.predict(new_scaled)  # 0 = No, 1 = Yes
prob = model.predict_proba(new_scaled)  # [P(No), P(Yes)]
print('Prediction:', pred[0])
print('Probability [No, Yes]:', prob[0])